### ISSUE TITLE
layer_sequence_create doesn't work for Sequence Object Structs

### ISSUE THREAD

**Issue by KeeVeeGames** [YoYoGames/GameMaker-HTML5#297]
Currently, it is only possible to create sequences in rooms from sequence ids.

```js
layer_sequence_create(layer, x, y, seq_test);    // working correctly
layer_sequence_create(layer, x, y, sequence_get(seq_test));    // not working correctly
```
If you try to spawn a sequence from `sequence_get` or `sequence_create` it will create the first sequence in the project instead. This is due to the call of `yyGetInt32` inside `layer_sequence_create` on the `sequence_id` argument which always returns 0 for sequence object structs.

In other runtimes it works correctly and spawns sequences from both ids and sequence structs.

I implemented correct sequence creation that now accepts both indexes and sequence structs.

**Comment by stuckie** [comment]
Can we get a project to verify against?

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.
