### ISSUE TITLE
instance_position incorrectly returns boolean instead of instance ID

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GameMaker-HTML5#354]
The implementation doesn't match documentation nor previous expected behavior.
[Doc](https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Asset_Management/Instances/instance_position.htm)

**Comment by biyectivo** [comment]
This has been fixed in the most current HTML5 runner:

https://github.com/YoYoGames/GameMaker-Bugs/issues/1682

**Comment by stuckie** [comment]
Closing as above.
