### ISSUE TITLE
HTML5: `string_trim_end()` does nothing

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-HTML5#372]
string_trim_end does nothing
test code:
```
var _str = string_format(1, 100, 10)
var _str = string_trim_end(_str, ["0"]);
var _str = string_trim_end(_str, ["."]);
var _str = string_trim_start(_str, [" "]);
show_debug_message(_str)
```

**Comment by Sidorakh** [comment]
Narrowed this down to a problem with the [`g_EscapeRegexRE`](https://github.com/YoYoGames/GameMaker-HTML5/blob/develop/scripts/functions/Function_String.js#L1096) regular expression - the original expression blocked a range of characters between \ and /, including all numbers and some symbols. Using this regular expression instead appears to fix it: `new RegExp("[\\/\\-\\\\^$*+?.()|[\\]{}]", "g");`

I've also opened a pull request with this fix, it appears to work nicely
