### ISSUE TITLE
SDF for html5

### ISSUE THREAD

**Issue by GINOFM** [YoYoGames/GameMaker-HTML5#389]
Hi, why in the current branch the SDF effect for font its not enabled?? In the 2023.08.0-main branch I can use the SDF effect in the web export without any error.

**Comment by rwkay** [comment]
What are you using as the current branch? develop is our current branch and 2023.11.0-main is the new branch for the November release.

**Comment by GINOFM** [comment]
As the current branch I am using the 2023.08.0 , but when I pulled the last branch (2023.11.0-main) I noticed that I can't use the SDF font in the web version but in the old branch yes (2023.08.0-main)

**Comment by stuckie** [comment]
We don't support *runtime* SDF fonts ( font_add ) for HTML5 targets, but it can be done if added through the IDE.
