### ISSUE TITLE
Clarify the licence being used

### ISSUE THREAD

**Issue by cher-nov** [YoYoGames/GameMaker-HTML5#44]
https://github.com/YoYoGames/GameMaker-HTML5/blob/85e8335ccdd95d063ea55e90d031023364abeae8/licence.txt#L3

https://github.com/YoYoGames/GameMaker-HTML5/blob/85e8335ccdd95d063ea55e90d031023364abeae8/package.json#L11

**Comment by rwkay** [comment]
It is under Apache licence

**Comment by cher-nov** [comment]
> It is under Apache licence

Yep, but right now it looks like dual licensing, which is probably not what you want.
