### ISSUE TITLE
Audio Pitch Crash on Opera

### ISSUE THREAD

**Issue by Yokinman** [YoYoGames/GameMaker-HTML5#45]
For Opera browsers, setting the pitch of an instance of a sound below 0.1 caused a crash (this might not be the specific value, but it was around there). As in, `audio_sound_pitch(audio_play_sound(snd, 0, false), 0.01)`.

**Comment by rwkay** [comment]
You need to have a project to illustrate the problem - the smaller the better to show the problem.

Is this specifically the Opera Browser? or Opera GX? or are you referring to the GX.games target within GameMaker (that is not the HTML5 Runner).

**Comment by Yokinman** [comment]
HTML5 export played on an Opera browser yeah. I was pitching down a sound over time to make a neat effect essentially.

**Comment by toby-yoyo** [comment]
Chromium-based browsers will throw an exception if the playback rate for streamed sounds is outside of the range 0.0625-16.

Firefox will mute audio outside of the range 0.125-8.

Raised [GM-6296](https://bugs.opera.com/browse/GM-6296) for some better handling and documentation of this quirk.

**Comment by toby-yoyo** [comment]
In the 2023.2 release, streamed sounds no longer use the node which was throwing this exception. They also now have the same limitless pitch range that unstreamed sounds have.

Closing this as completed.
