### ISSUE TITLE
"event_perform" Crash

### ISSUE THREAD

**Issue by Yokinman** [YoYoGames/GameMaker-HTML5#46]
Calling an instance's event on HTML5 versions crashes the game for step events and alarm events (but not draw events?). As in, `event_perform(ev_alarm, 0)` or `event_perform(ev_step, ev_step_end)`. I don't have access to HTML5 export as of the past couple days(?) so I can't test this issue further, but I experienced the issue within the past week.

**Comment by rwkay** [comment]
You need to have a project to illustrate the problem - the smaller the better to show the problem.

**Comment by DiasFranciscoA** [comment]
The issue has been resolved already. It may have been occurring in instances that were created using instance_create_* and initializing struct parameters were passed.
