### ISSUE TITLE
Access to the feature "gamepad" is disallowed by permissions policy

### ISSUE THREAD

**Issue by SnoutUp** [YoYoGames/GameMaker-HTML5#48]
Hello,

First of all, thank you for open sourcing this! Github Issues is much easier to use for bug reports, so I'm gonna try it out with one relatively frequent stack trace I see in Poki dashboard. 

`SecurityError: Failed to execute 'getGamepads' on 'Navigator': Access to the feature "gamepad" is disallowed by permissions policy.
`

Happens on Chrome, Opera and Edge.

I assume/hope (not confirmed) this doesn't cause a full game crash, but maybe could be cleaned up.

**Comment by gnysek** [comment]
Isn't this only for non-https websites?

(source: https://news.thewindowsclub.com/google-chrome-now-blocks-gamepad-access-on-insecure-websites-101927/ )
