### ISSUE TITLE
Contributing Guidance

### ISSUE THREAD

**Issue by kopelli** [YoYoGames/GameMaker-HTML5#50]
Having README.md and CONTRIBUTING.md files would be beneficial for those who come across the repo from sources other than https://gamemaker.io/en/blog/html5-open-source.

**Comment by cenowador** [comment]
This is very important. I have questions regarding contributions: will the team accept PRs that contain new features, or just bug fixes? For example: if I implemented a bunch of functions that enable cookies manipulation, would the team accept it as part of the runtime or prefer it to be made as an extension?

**Comment by rwkay** [comment]
adding new functions should be done in an extension, as we prefer it to be symmetrical across all platforms.

**Comment by yoyo-danielc** [comment]
Closing as we now have a `README.md` incl. contributing guidelines.
