### ISSUE TITLE
WebGPU and TypeScript Support

### ISSUE THREAD

**Issue by yjgaia** [YoYoGames/GameMaker-HTML5#512]
I understand that the GameMaker HTML5 Runner currently supports WebGL. Do you have any plans to support the latest technology, WebGPU? Additionally, do you plan to create type definition files to allow the runner to be used in TypeScript projects?

**Comment by rwkay** [comment]
We have already said that our new runtime GMRT will support WebGPU see https://www.youtube.com/watch?v=oyn9P3wK1qA and the video from last year https://gamemaker.io/en/blog/gamemaker-update-2023 where we started outlining the plans.
