### ISSUE TITLE
In-Game: [HTML5] Scribble does not run if built using 2024.6 or 2024.8 runtimes

### ISSUE THREAD

**Issue by Valcoran** [YoYoGames/GameMaker-HTML5#519]
JujuAdams doesn't officially support HTML5 for Scribble, so I'm raising the issue here as well on Tabby Fax's suggestion. 

This is the error I get when trying to open my project in HTML5 after the update:

Uncaught SyntaxError: redeclaration of const kgml_Script_anon_2634___scribble_gen_7_build_pages___scribble_gen_7_build_pages
[Forest Shack 3.js:36421:7](http://127.0.0.1:51264/html5game/Forest%20Shack%203.js?cachebust=382007149)note: Previously declared at line 36420, column 7[Forest Shack 3.js:36420:7](http://127.0.0.1:51264/html5game/Forest%20Shack%203.js?cachebust=382007149)
Uncaught ReferenceError: GameMaker_Init is not defined
http://127.0.0.1:51264/index.html:110

And this is the error I get when trying to open in HTML5 the latest Scribble.yyp project version freshly downloaded from github:

unreachable code after return statement
[Scribble.js:72393:2](http://127.0.0.1:51264/html5game/Scribble.js?cachebust=2084665280)
unreachable code after return statement
[Scribble.js:74227:2](http://127.0.0.1:51264/html5game/Scribble.js?cachebust=2084665280)
unreachable code after return statement
[Scribble.js:74431:2](http://127.0.0.1:51264/html5game/Scribble.js?cachebust=2084665280)
unreachable code after return statement
[Scribble.js:74443:2](http://127.0.0.1:51264/html5game/Scribble.js?cachebust=2084665280)
Uncaught SyntaxError: redeclaration of const kgml_Script_anon_2634___scribble_gen_7_build_pages___scribble_gen_7_build_pages
[Scribble.js:75808:7](http://127.0.0.1:51264/html5game/Scribble.js?cachebust=2084665280)note: Previously declared at line 75807, column 7[Scribble.js:75807:7](http://127.0.0.1:51264/html5game/Scribble.js?cachebust=2084665280)
Uncaught ReferenceError: GameMaker_Init is not defined
http://127.0.0.1:51264/index.html:110
[index.html:110:17](http://127.0.0.1:51264/index.html)
http://127.0.0.1:51264/index.html:110

I rolled back the update to 4.1.201, and scribble works as intended in both my project and the clean scribble yyp.

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by rwkay** [comment]
Fixed in 2024.10
