### ISSUE TITLE
Invalid Token when using this repo to compile

### ISSUE THREAD

**Issue by c023-DeV** [YoYoGames/GameMaker-HTML5#535]
(IDE v2024.6.1.208 RT v2024.6.1.208)

After following the steps on how to use this repository ( downloaded developer branch and referenced the scripts folder in the HTML platform settings) I get:

Uncaught SyntaxError: Unexpected token '{' 
and
Uncaught ReferenceError: GameMaker_Init is not defined
    at game.html:116

Tested with default settings and custom html.

Tested with Brave and Chrome Browsers.

Are there any other steps required? Or am I doing something wrong?

**Comment by c023-DeV** [comment]
Issue resolved with new update v2024.8

**Comment by rwkay** [comment]
Closing as above...
