### ISSUE TITLE
Manual Content: sprite_prefetch() page needs to clarify it is only supported on HTML5 if WebGL is enabled

### ISSUE THREAD

**Issue by MrOnsku** [YoYoGames/GameMaker-HTML5#537]
sprite_prefetch is in GameMaker-HTML5 [here](https://github.com/YoYoGames/GameMaker-HTML5/blob/c2ef47f7f964449e7757778ddf786b46c4caf839/scripts/functions/Function_Sprite.js#L1583) yet it is not supported in HTML5 builds.
https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Sprites/Sprite_Manipulation/sprite_prefetch_multi.htm

**Comment by stuckie** [comment]
It is not fully supported; it should work on WebGL but not on Canvas.
