### ISSUE TITLE
HTML5: sprite_delete() has no return

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-HTML5#546]
sprite_delete should return a bool but on the HTML5 source it has no return

this causes checks to incorrectly appear to be failing

![image](https://github.com/user-attachments/assets/af8b5c9a-857c-4f8a-b275-42c45f70119f)

HTML5:
![image](https://github.com/user-attachments/assets/27c8842d-9a54-472d-abaf-ec1d3f3a7799)

Windows:
![image](https://github.com/user-attachments/assets/7f808dca-419b-4d70-9c49-7a50edb1e19e)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2026.100.0.1152  Runtime v2026.100.0.1101
