### ISSUE TITLE
surface_create and surface_resize not working after game started

### ISSUE THREAD

**Issue by RowanFuture** [YoYoGames/GameMaker-HTML5#579]
I have tested 2 projects and surface_create and surface_resize isn't working in either of them after the game has already started,
I'm also not getting an error saying surface_set_target() is setting a non-existent surface, so I'm not sure what is happening at all
the surface is either invisible, or in the case of application_surface, it just never gets resized

would appreciate any advice/ a workaround? not sure what to do
is there a runtime in which these are certain to work so I can switch to it?

**Comment by stuckie** [comment]
This should be fixed in the current beta.

**Comment by RowanFuture** [comment]
> This should be fixed in the current beta.

It is, thank you!
