### ISSUE TITLE
SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.

### ISSUE THREAD

**Issue by SnoutUp** [YoYoGames/GameMaker-HTML5#59]
Hello,

Would like to report another crash which happens in newer Safari browsers and only appeared in latest GameMaker runtimes (2022.03 is the last "safe" one as far as I know). It is present in LTS too.

```
SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.
  at ? [html5game/BaconMayDie.js:6926:]
```
Unfortunately, I cannot provide any more details, because this is all what stack trace shows. 

Here's a StackOverflow thread talking about what seems to be this exact error:  
https://stackoverflow.com/questions/60026651/

Hope someone figures out where to look for this issue.

**Comment by DiasFranciscoA** [comment]
Hello, could you please provide us with a simple project demo that has this issue.

**Comment by SnoutUp** [comment]
> Hello, could you please provide us with a simple project demo that has this issue.

Unfortunately, I can't provide a demo project, because the only way I'm getting these crash reports is via publishing completed game(s) on Poki and watching their error dashboard. Eventually I will have to build and publish an update or a new game with a GM version newer than 2022.03 and if it will still have these crashes, I will send a full project to support.

**Comment by RowanFuture** [comment]
> > Hello, could you please provide us with a simple project demo that has this issue.
> 
> Unfortunately, I can't provide a demo project, because the only way I'm getting these crash reports is via publishing completed game(s) on Poki and watching their error dashboard. Eventually I will have to build and publish an update or a new game with a GM version newer than 2022.03 and if it will still have these crashes, I will send a full project to support.

would it be possible to show the code where the error is happening? / so that we can narrow in on what part is causing the issue

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.
