### ISSUE TITLE
draw_text_bla() alignment in HTML5 is different to desktop export alignment?

### ISSUE THREAD

**Issue by Amon-Arelious-Soza** [YoYoGames/GameMaker-HTML5#64]
I have a simple test yyz for you guys to see. It seems when placing text via draw_text functions the position is different when exported to HTML5. If I align things for desktop they work and are where I placed them but the text in html5 is way off.

[HTML5TestText](https://panayiotisyianni.com/mygames/htmlTextTest.yyz)

Download the yyz. Export to desktop target and check where the text is in the white square. Now export to html5 and you will see the text alignment is completely off.

**Comment by biyectivo** [comment]
Actually not... at least not in my system
<img width="388" alt="image" src="https://github.com/YoYoGames/GameMaker-HTML5/assets/28306587/f4599f3b-4016-4fd0-9177-12ded56c7be8">

What version are you using?

**Comment by biyectivo** [comment]
Also your code is not correct, you are doing:

```
draw_set_halign(true);
draw_set_valign(true);
```

This is incorrect, these functions receive one of these values:
```
fa_left / fa_top
fa_center / fa_middle
fa_right / fa_bottom
```

The only reason this works is because `true` casts to 1, which is also the value of `fa_center` / `fa_middle`

**Comment by stuckie** [comment]
Closing as above
