### ISSUE TITLE
Empty structs added to structs in debug mode (Chrome)

### ISSUE THREAD

**Issue by Gizmo199** [YoYoGames/GameMaker-HTML5#99]
```
var struct = {
	foo : { this : 1 },
	bar : { this : 2 }
}

var names = variable_struct_get_names(struct);
for ( var i=0; i<array_length(names); i++ ){
	show_debug_message(names[i]);
}
```
Running this code in debug mode will produce empty struct references in the main struct. 

![issue](https://user-images.githubusercontent.com/25496262/211050511-9fc72364-b07d-45b6-8349-6a1db5dccd1d.png)

**Comment by rwkay** [comment]
Unable to replicate with 2024.600.0.580 runtime... I suspect that this has been fixed in an earlier commit
